title: "Nguyen Hai Truong - Google Developer Expert | Cloud & Open Source"
author: "Nguyen Hai Truong"
email: nguyenhaitruonghp@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Expert insights on Google Cloud Platform, Kubernetes, serverless computing, and open source technologies. 
  Technical tutorials, best practices, and real-world solutions from a Google Developer Expert.
  Covering GCP, Cloud Run, Vertex AI, Gemini, container orchestration, and modern DevOps practices.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

# Permalink configuration for concise URLs
permalink: /:title.html

plainwhite:
  name: Nguyen Hai Truong
  tagline: "Google Developer Expert | Cloud Architect | Open Source Enthusiast"
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  analytics_id: "G-3BVZ3G2PM7" # Google Analytics 4 Measurement ID
  condensed_mobile:
  # Navigation menu
  navigation:
    - title: "<img src='/assets/@home.png' alt='Home' style='width: 18px; height: 18px; vertical-align: middle;'>"
      url: "/"
  # generate social links in footer
  social_links:
    twitter: truongnh92
    github:  truongnh1992
    linkedIn: in/truongnh1992
    #dribbble: jekyll
    #flickr:   jekyll
    instagram: haitruonghp
    #pinterest: jekyll
    #youtube: jekyll


remote_theme: samarsault/plainwhite-jekyll

# SEO and site optimization
url: "https://truongnh1992.github.io" # Your site URL
baseurl: "" # Leave empty for GitHub Pages
lang: "en-US"
timezone: "Asia/Ho_Chi_Minh"

# SEO Keywords for your niche
keywords: "Google Cloud Platform, GCP, Kubernetes, Serverless, Cloud Run, Vertex AI, Gemini, Open Source, DevOps, Container Orchestration, Cloud Architecture, Google Developer Expert"

# Social media defaults
social:
  name: "Nguyen Hai Truong"
  links:
    - "https://twitter.com/truongnh92"
    - "https://github.com/truongnh1992"
    - "https://linkedin.com/in/truongnh1992"
    - "https://instagram.com/haitruonghp"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
