# SITE CONFIGURATION
#baseurl: ""
url: "https://truongnh.gdgcloudhanoi.com"

# THEME-SPECIFIC CONFIGURATION
title: "Nguyen Hai-Truong's Blog"                                    # site's title
description: "Linux Tech Blog"                                # used by search engines
#avatar: static/img/GDG.png                                  # Empty for no avatar in navbar
#favicon: static/img/favicon.ico                                   # Icon displayed in the tab

# Header and footer text
header_text: "Learn something new, everyday."                                # Change Blog header text
# header_feature_image: static/img/computer.jpeg 
footer_text: Powered by <a href="https://gdgcloudhanoi.com/">GDG Cloud Hanoi</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: static/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-126117321-1                        # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: truongnh-bk55-github-io               # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons: ["facebook", "twitter", "linkedin"]       # In _data/social.yml
share_buttons: facebook                                 # In _data/social.yml
authors: truongnh                                       # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

