title: "Linux Tech Blog"
description: My Personal Tech Blog
author: truongnh1992
github: https://github.com/truongnh1992
about: ""
disqus_shortname: truongnh-bk55-github-io
google_analytics: UA-126117321-1
avatar_url: /static/img/mymac.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/haitruong.bkhn"
    - icon: fa-twitter
      link: "https://twitter.com/truongnh92"
    - icon: fa-youtube
      link: "https://www.youtube.com/user/nhtbkhn"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/nguyen-hai-truong-hp"
    - icon: fa-github
      link: "https://github.com/truongnh1992"
    - icon: fa-envelope
      link: "mailto:haitruong-hust@bka.vn"

share:
  twitter_username: truongnh92
#  fb_appid: 1749788565247320

urls:
    - text: About me
      url: /about/
    - text: Linux
      url: /category/linux
    - text: Kubernetes
      url: /category/kubernetes
    - text: Networking
      url: /category/networking
    - text: Python
      url: /category/python
    - text: Golang
      url: /category/golang
    - text: Tutorials
      url: /category/tutorials
    - text: Raspberry Pi
      url: /category/raspberry

url: "https://truongnh1992.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
